# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
asciidoctorj = "3.0.1"
hamcrest = "3.0"
junit = "5.14.1"

[libraries]
org-asciidoctor-asciidoctorj = { module = "org.asciidoctor:asciidoctorj", version.ref = "asciidoctorj" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

